modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="alan_walker_mod"
version="1.1"
displayName="Alan Walker Mod"
displayURL="https://florianmeixnerdev.4lima.de"
logoFile="logo.png"
credits="Creator: Florian Meixner "
authors="FlorianMeixnerDEV"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.alan_walker_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alan_walker_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration